name: Monorepo Split

on:
  workflow_call:

permissions:
  contents: read

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: packages/magento2-module-restrictions
            split_repo: magento2-module-restrictions
          - local_path: packages/magento2-module-inpost-pay
            split_repo: magento2-module-inpost-pay
          - local_path: packages/magento2-module-inpost-pay-graph-ql
            split_repo: magento2-module-inpost-pay-graph-ql
          - local_path: packages/magento2-module-inpost-pay-commerce
            split_repo: magento2-module-inpost-pay-commerce
          - local_path: packages/magento2-module-restrictions-commerce
            split_repo: magento2-module-restrictions-commerce
          - local_path: packages/magento2-module-inpost-pay-hyva-checkout
            split_repo: magento2-module-inpost-pay-hyva-checkout
          - local_path: packages/magento2-module-inpost-pay-hyva-theme
            split_repo: magento2-module-inpost-pay-hyva-theme
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_REPO_ACCESS_TOKEN }}
        with:
          package_directory: ${{ matrix.package.local_path }}
          repository_organization: inpost
          repository_name: ${{ matrix.package.split_repo }}
          tag: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
